### ISSUE TITLE
翻译申请：Web 应用部署

### ISSUE THREAD

**Issue by ghost** [haiiiiiyun/fullstackpython.cn#6]
你好，申请尝试从**Web 应用部署** 部分开始翻译，多谢！

**Comment by haiiiiiyun** [comment]
效率好高！好的，谢谢！

**Comment by ghost** [comment]
暑假比平时要闲点，尽量每天坚持翻译一篇也能学到不少东西，而且中途还会顺便查阅其他资料，挺好的。不过我觉得你的翻译真的很好，值得学习。
